onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@swc/core"
  - dtrace-provider
  - esbuild
  - spawn-sync
publicHoistPattern:
  - "@lingui/conf"
overrides:
  entities: ^6.0.1
  parse5: $fake-parse5
  parse5-htmlparser2-tree-adapter: $fake-parse5
