// Generated by IcedCoffeeScript 1.4.0c
(function() {

  window.URL_CONST = {
    'login': 'https://learn.tsinghua.edu.cn/MultiLanguage/lesson/teacher/loginteacher.jsp',
    'course': 'http://learn.tsinghua.edu.cn/MultiLanguage/lesson/student/MyCourse.jsp',
    'course_all': 'http://learn.tsinghua.edu.cn/MultiLanguage/lesson/student/MyCourse.jsp?typepage=2',
    'notification': 'https://learn.tsinghua.edu.cn/MultiLanguage/public/bbs/getnoteid_student.jsp',
    'course_info': 'https://learn.tsinghua.edu.cn/MultiLanguage/lesson/student/course_info.jsp',
    'file': 'https://learn.tsinghua.edu.cn/MultiLanguage/lesson/student/download.jsp',
    'resource': 'https://learn.tsinghua.edu.cn/MultiLanguage/lesson/student/ware_list.jsp',
    'deadline': 'https://learn.tsinghua.edu.cn/MultiLanguage/lesson/student/hom_wk_brw.jsp',
    'mentor': 'https://learn.tsinghua.edu.cn/MultiLanguage/public/bbs/getbbsid_student.jsp',
    'discuss': 'https://learn.tsinghua.edu.cn/MultiLanguage/public/bbs/gettalkid_student.jsp',
    'course_page': 'https://learn.tsinghua.edu.cn/MultiLanguage/lesson/student/course_locate.jsp',
    'deadline_detail': 'http://learn.tsinghua.edu.cn/MultiLanguage/lesson/student/hom_wk_detail.jsp',
    'deadline_submit': 'http://learn.tsinghua.edu.cn/MultiLanguage/lesson/student/hom_wk_submit.jsp',
    'deadline_review': 'http://learn.tsinghua.edu.cn/MultiLanguage/lesson/student/hom_wk_view.jsp'
  };

  window.CONST = {
    version: window.getManifest().version,
    featureName: ['deadline', 'notification', 'file'],
    collectNumber: 20,
    collectEvalLimit: 7,
    GUIListName: {
      deadline: '#nearby-deadline',
      notification: '#category-heading',
      file: '#file-heading',
      collect: '#js-new'
    },
    listTemp: ['collect', 'deadline', 'notification', 'file'],
    panelTran: {
      collect: 'main-page',
      deadline: 'deadline-page',
      notification: 'notification-page',
      file: 'file-page'
    },
    cacheListName: {
      courseList: 'course_list',
      deadline: 'deadline_list',
      notification: 'notification_list',
      file: 'file_list'
    },
    ignoreListName: {
      deadline: 'ignore_list_deadline',
      notification: 'ignore_list_notification',
      file: 'ignore_list_file'
    },
    changeState: {
      unread: {
        read: 'readed',
        star: 'stared'
      },
      readed: {
        read: 'readed',
        star: 'stared'
      },
      stared: {
        read: 'stared',
        star: 'readed'
      }
    },
    evalFlag: {
      EXPIRED: 2 << 13,
      READED: 0,
      UNREAD: -(2 << 15),
      STARED: -(2 << 16),
      SUBMIT: 2 << 8,
      HOMEWORK: -(2 << 3),
      HOMEWORK_TODAY: -(2 << 8)
    },
    stateTrans: {
      submitted: '已经提交',
      unsubmit: '尚未提交'
    }
  };

}).call(this);
