// Generated by IcedCoffeeScript 1.4.0c
(function() {
  var detailLoader, init;

  detailLoader = function(type, id) {
    if (type === 'file') return;
    return chrome.extension.sendMessage({
      op: 'detail',
      data: {
        type: type,
        id: id
      }
    }, function(response) {
      var d;
      console.log(response);
      d = response.data;
      $('.title').text(d.detail.title);
      $('.content').html(d.detail.content);
      $('.date').text(d.day);
      return $('.courseName').text(d.courseName);
    });
  };

  init = function() {
    var args;
    args = window.getURLParamters(window.location.href);
    return detailLoader(args.type, args.id);
  };

  $(function() {
    return init();
  });

}).call(this);
