// Generated by IcedCoffeeScript 1.4.0c
(function() {
  var args, detailLoader, init, update;

  args = new Object();

  detailLoader = function(type, id, force) {
    if (type === 'file') return;
    return chrome.extension.sendMessage({
      op: 'detail',
      force: force,
      data: {
        type: type,
        id: id
      }
    }, function(response) {
      var d;
      d = response.data;
      $('body').addClass(response.type);
      if (response.type === 'notification') {
        $('.noti-wrap').show();
        $('.title').text(d.detail.title);
        try {
          $('.content').html(d.detail.content);
        } catch (_error) {}
        $('.date').text(new Date(d.day).Format("yyyy-MM-dd"));
        $('.courseName').text(d.courseName);
        $('.author').text(d.author);
      } else if (response.type === 'deadline') {
        $('.ddl-wrap').show();
        $('.title').text(d.detail.title);
        try {
          $('.content').html(d.detail.content);
        } catch (_error) {}
        $('.date').text(new Date(d.end).Format("yyyy-MM-dd"));
        $('.courseName').text(d.courseName);
        try {
          $('.uploadText').html(d.detail.uploadText);
        } catch (_error) {}
        $('.uploadAttach').html(d.detail.uploadAttach);
        $('.attach').html(d.detail.attach);
      }
      $('.loading').hide();
      if (d.state === 'stared') return $('.action-star').addClass('stared');
    });
  };

  init = function() {
    args = window.getURLParamters(window.location.href.replace(/#*$/, ''));
    detailLoader(args.type, args.id, false);
    return $('.action-refresh').click(function(e) {
      e.preventDefault();
      return update();
    });
  };

  update = function() {
    $('.loading').show();
    $('.noti-wrap').hide();
    $('.ddl-wrap').hide();
    return detailLoader(args.type, args.id, true);
  };

  $(function() {
    $('.noti-wrap').hide();
    $('.ddl-wrap').hide();
    return init();
  });

}).call(this);
