name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build Chrome version
        run: pnpm zip:chrome
      - name: Upload Chrome version
        uses: actions/upload-artifact@v4
        with:
          name: chrome
          path: |
            dist/chrome-mv3/
            stats.html
      - name: Build Firefox version
        run: pnpm zip:firefox
      - name: Upload Firefox version
        uses: actions/upload-artifact@v4
        with:
          name: firefox
          path: |
            dist/firefox-mv3/
            stats.html
      - name: Upload Zip files
        uses: actions/upload-artifact@v4
        with:
          name: zip-files
          path: |
            dist/*.zip
